Repository elyra-ai/elyra, pull requests merged in 2020-04, with the labels that each got.

#392 Fix python editor interupted run bug
  packages/python-runner/src/widget.tsx
Labels: kind:bug

#405 added minor fix to read secure flag from params instead of constant
  elyra/util/cos.py
Labels: status:Waiting for Author

#420 Update package.json and remove `clean` script
  .gitignore
  packages/application/package.json
  packages/code-snippet/package.json
  packages/notebook-scheduler/package.json
  packages/pipeline-editor/package.json
  packages/python-runner/package.json
Labels: component:build

#421 initial code snipperts UI enhancements
  packages/code-snippet/src/CodeSnippet.ts
  packages/code-snippet/src/CodeSnippetWidget.tsx
  packages/code-snippet/src/ExpandableComponent.tsx
  packages/code-snippet/style/index.css
Labels: area:front-end, component:code-snippets
