Repository elyra-ai/elyra, pull requests merged in 2020-11, with the labels that each got.

#1020 Fix jest tests
  package.json
Labels: Hacktoberfest

#985 Add search and tag to metadata
  elyra/metadata/schemas/code-snippet.json
  elyra/metadata/schemas/kfp.json
  elyra/metadata/schemas/runtime-image.json
  packages/code-snippet/src/CodeSnippetWidget.tsx
  packages/metadata-common/src/FilterTools.tsx
  packages/metadata-common/src/MetadataEditor.tsx
  packages/metadata-common/src/MetadataEditorTags.tsx
  packages/metadata-common/src/MetadataWidget.tsx
  packages/metadata-common/style/index.css
  packages/metadata/style/index.css
  packages/pipeline-editor/src/RuntimesWidget.tsx
  packages/ui-components/src/icons.tsx
  packages/ui-components/style/icons/tag.svg
Labels: Hacktoberfest, area:front-end, component:code-snippets, component:metadata

#1065 Update to JupyterLab-git 0.23.1
  Makefile
  README.md
  docs/source/getting_started/installation.md
  setup.py
Labels: component:git-integration

#1086 Add documentation documentation to the Developer Guide
  docs/source/developer_guide/documentation.md
  docs/source/index.rst
Labels: area:documentation

#1109 refresh overview content
  docs/source/getting_started/overview.md
Labels: area:documentation

#1100 add "getting help" doc topic
  docs/source/getting_started/getting-help.md
  docs/source/index.rst
Labels: area:documentation

#1111 Update runtime config documentation
  docs/source/images/access-runtime-configurations.png
  docs/source/images/runtime-access-config.png
  docs/source/images/runtime-create-config.png
  docs/source/user_guide/runtime-conf.md
Labels: area:documentation
