Repository elyra-ai/elyra, pull requests merged in 2020-05, with the labels that each got.

#476 Properly include dependencies recursively
  elyra/util/archive.py
  elyra/util/tests/test_archive.py
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
Labels: jupyterlab 1.x

#480 Use schema-driven approach for metadata application
  docs/source/developer_guide/metadata.md
  docs/source/user_guide/runtime-conf.md
  elyra/__init__.py
  elyra/metadata/__init__.py
  elyra/metadata/code_snippet.py
  elyra/metadata/metadata.py
  elyra/metadata/metadata_app.py
  elyra/metadata/metadata_app_utils.py
  elyra/metadata/mixins.py
  elyra/metadata/runtime.py
  elyra/metadata/schemas/code-snippet.json
  elyra/metadata/schemas/kfp.json
  elyra/metadata/schemas/test.json
  elyra/metadata/tests/conftest.py
  elyra/metadata/tests/test_handlers.py
  elyra/metadata/tests/test_metadata.py
  elyra/metadata/tests/test_metadata_app.py
  elyra/metadata/tests/test_runtime_app.py
  elyra/metadata/tests/test_utils.py
  elyra/pipeline/processor_kfp.py
  setup.py
Labels: ReleaseNote needed, jupyterlab 1.x

#505 Merge notebook-scheduler into pipeline-editor
  Makefile
  README.md
  docs/source/getting_started/installation.md
  packages/notebook-scheduler/package.json
  packages/notebook-scheduler/src/index.tsx
  packages/notebook-scheduler/src/json-loader.d.ts
  packages/notebook-scheduler/style/index.css
  packages/notebook-scheduler/tsconfig.json
  packages/pipeline-editor/package.json
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/pipeline-editor/src/SubmitNotebook.ts
  packages/pipeline-editor/src/index.ts
  packages/pipeline-editor/src/pipeline-template.json
  packages/pipeline-editor/src/utils.ts
  packages/pipeline-editor/style/index.css
  packages/pipeline-editor/tsconfig.json
Labels: kind:Needs Release Note

#542 Update pipeline node tooltip to display boolean props
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
Labels: component:pipeline-editor

#552 Update JupyterLab TOC extension to 4.0.0
  Makefile
Labels: component:toc extension
