Repository elyra-ai/elyra, pull requests merged in 2020-09, with the labels that each got.

#907 Update installation instructions
  docs/source/getting_started/installation.md
Labels: area:documentation

#908 Update default runtime images
  etc/config/metadata/runtime-images/anaconda.json
  etc/config/metadata/runtime-images/pandas.json
  etc/config/metadata/runtime-images/tensorflow_2x_gpu_py3.json
  etc/config/metadata/runtime-images/tensorflow_2x_py3.json
Labels: component:build, component:pipeline-runtime

#909 add tutorial section to the documentation
  docs/source/getting_started/tutorials.md
  docs/source/index.rst
Labels: area:documentation

#919 Update doc build requirements
  docs/requirements.txt
Labels: area:documentation, kind:bug

#927 Pipeline export: update file format labels
  packages/pipeline-editor/src/PipelineExportDialog.tsx
Labels: component:pipeline-editor

#915 add runtime Docker image creation doc
  docs/source/index.rst
  docs/source/recipes/creating-a-custom-runtime-image.md
  docs/source/user_guide/runtime-image-conf.md
Labels: area:documentation, kind:enhancement

#929 add link to openshift deployment instructions
  docs/source/getting_started/installation.md
Labels: area:documentation, platform:OpenShift
