Repository elyra-ai/elyra, pull requests merged in 2021-08, with the labels that each got.

#1980 Document backend build
  Makefile
  docs/source/developer_guide/development-workflow.md
Labels: area:documentation, chore

#2004 Update pipeline validation label check
  elyra/pipeline/validate.py
Labels: approved, blocker

#2005 Add missing node label for single file pipeline submission
  elyra/pipeline/validate.py
  packages/pipeline-editor/src/pipeline-template.json
  packages/pipeline-editor/src/utils.ts
Labels: blocker

#2026 Improve issue-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: chore

#2034 Proposal to relax kfp sdk dependency
  setup.py
Labels: component:build

#1995 Add Describe Command to CLI
  docs/source/user_guide/pipelines.md
  elyra/cli/pipeline_app.py
  elyra/cli/tests/test_pipeline_app.py
Labels: impact:needs doc updates

#2070 Improve validation output in elyra-pipeline CLI
  elyra/cli/pipeline_app.py
  elyra/pipeline/validate.py
Labels: component: CLI-tools
