Repository elyra-ai/elyra, pull requests merged in 2021-07, with the labels that each got.

#1803 Document best practices for file-based nodes in user guide
  docs/source/images/user_guide/elyra-env-vars.png
  docs/source/images/user_guide/vpe-node-env-vars.png
  docs/source/images/user_guide/vpe-node-input-files.png
  docs/source/images/user_guide/vpe-node-output-files.png
  docs/source/index.rst
  docs/source/user_guide/best-practices-file-based-nodes.md
  docs/source/user_guide/runtime-image-conf.md
Labels: area:documentation

#1844 Add left palette option to PipelineEditor props
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/pipeline-editor/src/pipelineProperties.ts
  packages/pipeline-editor/style/index.css
Labels: upstream

#1891 Update Pipeline Editor to 0.10.1
  packages/pipeline-editor/package.json
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  yarn.lock
Labels: blocker

#1839 Add 'Pipeline components' topic to the user guide
  docs/source/images/user_guide/pipeline-components/custom-kubeflow-components-in-palette.png
  docs/source/images/user_guide/pipeline-components/example-components-pipeline.png
  docs/source/images/user_guide/pipeline-components/generic-components-in-palette.png
  docs/source/images/user_guide/pipeline-components/kubeflow-pipeline.png
  docs/source/index.rst
  docs/source/user_guide/pipeline-components.md
Labels: area:documentation

#1848 Update 'pipelines' topic in User Guide
  docs/source/images/user_guide/pipelines/add-comment-to-node.gif
  docs/source/images/user_guide/pipelines/add-component-from-palette.gif
  docs/source/images/user_guide/pipelines/add-components-from-file-browser.gif
  docs/source/images/user_guide/pipelines/add-components-from-palette.gif
  docs/source/images/user_guide/pipelines/configure-node.gif
  docs/source/images/user_guide/pipelines/configure-pipeline-export-options.png
  docs/source/images/user_guide/pipelines/configure-pipeline-run-options.png
  docs/source/images/user_guide/pipelines/connect-nodes.gif
  docs/source/images/user_guide/pipelines/editor-links.png
  docs/source/images/user_guide/pipelines/generic-pipeline.png
  docs/source/images/user_guide/pipelines/pipeline-editor-export.png
  docs/source/images/user_guide/pipelines/pipeline-editor-run.png
  docs/source/images/user_guide/pipelines/pipeline-editor.png
  docs/source/images/user_guide/pipelines/pipeline-properties.png
  docs/source/images/user_guide/pipelines/pipelines-nodes.png
  docs/source/images/user_guide/pipelines/runtime-specific-pipeline.png
  docs/source/user_guide/pipelines.md
Labels: area:documentation

#1860 Enable migration from previous pipeline versions
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/pipeline-editor/src/constants.ts
  packages/pipeline-editor/src/index.ts
  packages/pipeline-editor/src/utils.ts
Labels: blocker, upstream

#1945 Update Apache Airflow jinja template DAG creation logic
  elyra/templates/airflow/airflow_template.jinja2
Labels: blocker

#1950 Update Airflow operation naming for uniqueness
  elyra/pipeline/processor_airflow.py
Labels: blocker

#1919 Overview documentation: update tutorial references
  docs/source/getting_started/tutorials.md
Labels: approved, area:documentation

#1961 Update operation naming for airflow custom components
  elyra/pipeline/processor_airflow.py
  elyra/pipeline/tests/test_processor_airflow.py
Labels: platform: pipeline-Airflow

#1933 Update 'runtime image configuration' topic in User Guide
  docs/source/images/user_guide/runtime-image-conf/cmd-palette-manage-images.png
  docs/source/images/user_guide/runtime-image-conf/runtime-images-ui.png
  docs/source/images/user_guide/runtime-image-conf/sidebar-manage-images-button.png
  docs/source/images/user_guide/runtime-image-conf/toolbar-manage-images-button.png
  docs/source/user_guide/runtime-image-conf.md
Labels: approved, area:documentation, chore

#1917 Update JupyterLab launcher page image in README
  README.md
  docs/source/images/elyra-main-page.png
Labels: area:documentation, chore

#1968 Set KFP component display name to the provided label name
  elyra/pipeline/processor_kfp.py
Labels: approved, component:pipeline-runtime, platform: pipeline-Kubeflow

#1982 Bypass failing kfp component tests temporarily
  elyra/pipeline/tests/test_processor_kfp.py
Labels: approved

#1974 Refactor component location to jupyter/shared/components/runtime
  elyra/pipeline/component.py
  elyra/pipeline/processor_kfp.py
  etc/config/components/airflow/slack_operator.py
  etc/config/components/kfp/filter_text_using_shell_and_grep.yaml
  etc/config/components/kfp/kubeflow_serve_model_using_kfserving.yaml
  etc/config/components/kfp/run_notebook_using_papermill.yaml
  etc/config/components/kfp_component_catalog.json
  setup.py
Labels: doc/examples-follow-up-required

#1971 Uncap jinja2 and nbconvert dependency version
  setup.py
Labels: blocker

#1664 Validation service initial implementation
  elyra/elyra_app.py
  elyra/pipeline/handlers.py
  elyra/pipeline/parser.py
  elyra/pipeline/pipeline.py
  elyra/pipeline/tests/resources/validation_pipelines/NotebookA.ipynb
  elyra/pipeline/tests/resources/validation_pipelines/aa_invalid_node_op.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_basic_filepath_check.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_basic_pipeline_only_notebook.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_basic_pipeline_with_scripts.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_double_cycle.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_invalid_node_property_dependency_file_path.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_invalid_node_property_hardware_resources.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_invalid_node_property_image_name.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_invalid_node_property_structure.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_malformed_basic_pipeline_only_notebook.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_single_cycle.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/generic_singleton.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/kf_invalid_node_op.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/kf_invalid_node_op_with_supernode.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/kf_invalid_node_property_in_component.pipeline
  elyra/pipeline/tests/resources/validation_pipelines/subdirectoryA/TestFileA.txt
  elyra/pipeline/tests/test_pipeline_parser.py
  elyra/pipeline/tests/test_validation.py
  elyra/pipeline/validate.py
  packages/ui-components/src/RequestErrors.tsx
  setup.py
Labels: blocker

#1972 Handle connection error when fetching kfp session cookie
  elyra/pipeline/processor_kfp.py
Labels: approved

#1987 Improve 'run notebook' component specification
  etc/config/components/kfp/run_notebook_using_papermill.yaml
Labels: approved
