Repository elyra-ai/elyra, pull requests merged in 2021-05, with the labels that each got.

#1635 Add configuration instruction for KF 1.3
  docs/source/recipes/using-elyra-with-kubeflow-notebook-server.md
Labels: area:documentation

#1641 Add tested version information to prerequisites
  docs/source/user_guide/runtime-conf.md
Labels: area:documentation

#1642 Fix KF Dex authentication bug
  elyra/pipeline/processor_kfp.py
Labels: component:pipeline-runtime, platform: Kubeflow

#1676 Add validation section to runtime configuration topic in the user guide
  docs/source/user_guide/runtime-conf.md
Labels: area:documentation

#1654 Add support for updating env vars
  Makefile
  docs/source/developer_guide/development-workflow.md
  packages/pipeline-editor/package.json
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/pipeline-editor/src/nodes/notebook.ts
  packages/pipeline-editor/src/nodes/python.ts
  packages/pipeline-editor/src/nodes/r.ts
  packages/pipeline-editor/tsconfig.json
  yarn.lock
Labels: upstream

#1574 Update /recipes/deploying-elyra-with-opendatahub.md
  docs/source/images/odh-deploy-create-kfdef.png
  docs/source/images/odh-deploy-create-kfdef2.png
  docs/source/images/odh-deploy-create-project.png
  docs/source/images/odh-deploy-oc-login.png
  docs/source/images/odh-deploy-set-spawner-options.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/access-minio-gui.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/copy-jh-kfdef.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/deploy-app-using-operator.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/deploy-kubeflow-kfdef.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/install-odh-operator.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/jupyterlab-confirm-elyra-version.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/jupyterlab-open-terminal.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/open-runtime-configurations-list.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/openshift-get-login-command.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/openshift-open-projects.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/openshift-view-project.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/select-elyra-image-in-jh-spawner.png
  docs/source/images/recipes/deploying-elyra-with-opendatahub/select-kf-namespace.png
  docs/source/recipes/deploying-elyra-with-opendatahub.md
Labels: area:documentation, platform: Open Data Hub, platform:OpenShift

#1711 Normalize KFP endpoint URL
  elyra/pipeline/processor_kfp.py
Labels: component:pipeline-runtime, platform: pipeline-Kubeflow
