Repository elyra-ai/elyra, pull requests merged in 2021-03, with the labels that each got.

#1353 Update Runtime configuration topic in the User's Guide
  docs/source/user_guide/runtime-conf.md
Labels: area:documentation

#1352 Formalize titles and descriptions in AA and KFP schema
  elyra/metadata/schemas/airflow.json
  elyra/metadata/schemas/kfp.json
Labels: area:documentation

#1363 Remove trailing / from github api URL to prevent failures
  elyra/util/git.py
Labels: component:pipeline-runtime, kind:bug, platform: Airflow

#1367 Update Apache Airflow deployment documentation
  docs/source/images/airflow-runtime-config-sample.png
  docs/source/recipes/configure-airflow-as-a-runtime.md
  etc/docker/airflow/README.md
  etc/kubernetes/airflow/README.md
  etc/kubernetes/airflow/helm/values.yaml
Labels: area:documentation, platform: Airflow

#1393 Update runtime configuration topic
  docs/source/images/runtime-create-config.png
  docs/source/user_guide/runtime-conf.md
Labels: area:documentation

#1310 Add reference to Apache Airflow tutorial to documentation
  docs/source/getting_started/tutorials.md
Labels: area:documentation

#1432 Fixed Code Quality Issues
  elyra/metadata/metadata_app_utils.py
  elyra/metadata/storage.py
  elyra/metadata/tests/test_metadata.py
  elyra/metadata/tests/test_utils.py
  elyra/pipeline/tests/test_pipeline_parser.py
  elyra/util/archive.py
Labels: status:Waiting for Author

#1456 Use legacy resolver during binder build
  binder/postBuild
Labels: component:binder, jupyterhub

#1488 Fix container image build command
  docs/source/developer_guide/development-workflow.md
Labels: area:documentation

#1504 Pin version range of autopep8 due to version conflict
  setup.py
Labels: platform: Open Data Hub
