Repository elyra-ai/elyra, pull requests merged in 2021-11, with the labels that each got.

#2241 Generalize component reading and processing for BYO catalog-types
  docs/source/user_guide/pipeline-components.md
  elyra/contents/parser.py
  elyra/elyra_app.py
  elyra/metadata/manager.py
  elyra/metadata/metadata.py
  elyra/metadata/schema.py
  elyra/metadata/schemas/component-registry.json
  elyra/metadata/schemas/local-directory-catalog.json
  elyra/metadata/schemas/local-file-catalog.json
  elyra/metadata/schemas/meta-schema.json
  elyra/metadata/schemas/url-catalog.json
  elyra/metadata/schemaspaces.py
  elyra/metadata/schemasproviders.py
  elyra/pipeline/airflow/component_parser_airflow.py
  elyra/pipeline/airflow/processor_airflow.py
  elyra/pipeline/catalog_connector.py
  elyra/pipeline/component.py
  elyra/pipeline/component_metadata.py
  elyra/pipeline/component_registry.py
  elyra/pipeline/kfp/component_parser_kfp.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/pipeline_definition.py
  elyra/templates/airflow/airflow_template.jinja2
  elyra/templates/components/canvas_properties_template.jinja2
  elyra/tests/cli/resources/kfp_3_node_custom.pipeline
  elyra/tests/metadata/test_handlers.py
  elyra/tests/metadata/test_utils.py
  elyra/tests/pipeline/airflow/test_component_parser_airflow.py
  elyra/tests/pipeline/kfp/test_component_parser_kfp.py
  elyra/tests/pipeline/kfp/test_processor_kfp.py
  elyra/tests/pipeline/resources/sample_pipelines/pipeline_with_airflow_components.json
  elyra/tests/pipeline/resources/validation_pipelines/kf_inputpath_parameter.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_invalid_inputpath_missing_connection.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_invalid_inputpath_parameter.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_invalid_node_op.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_invalid_node_op_with_supernode.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_invalid_node_property_in_component.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_supernode_invalid_single_cycle.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_supernode_valid.pipeline
  etc/config/metadata/component-registries/elyra-airflow-filename-preconfig.json
  etc/config/metadata/component-registries/elyra-airflow-filesystem-preconfig.json
  etc/config/metadata/component-registries/elyra-airflow-url-preconfig.json
  etc/config/metadata/component-registries/elyra-kfp-directory-preconfig.json
  etc/config/metadata/component-registries/elyra-kfp-url-preconfig.json
  packages/metadata-common/src/AddMetadataButton.tsx
  packages/metadata-common/src/MetadataEditor.tsx
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/pipeline-editor/src/index.ts
  packages/services/src/test/application.spec.ts
  packages/ui-components/src/BooleanInput.tsx
  packages/ui-components/src/icons.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/style/icons/pipeline-components.svg
  packages/ui-components/style/index.css
  setup.py
  tests/integration/pipeline.ts
Labels: status:Test in Progress

#2257 Improve KF authentication handling
  docs/source/user_guide/runtime-conf.md
  elyra/metadata/schemas/kfp.json
  elyra/metadata/schemasproviders.py
  elyra/pipeline/kfp/kfp_authentication.py
  elyra/pipeline/kfp/kfp_metadata.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/runtimes_metadata.py
  elyra/templates/kfp/kfp_template.jinja2
Labels: component:pipeline-runtime

#2280 Add 'BYO component catalog connector' topic to 'developer guide'
  docs/source/developer_guide/pipeline-component-connectors.md
  docs/source/images/developer_guide/pipeline-component-connectors/component-catalogs.png
  docs/source/index.rst
Labels: area:documentation

#2282 Component catalogs schemaspace
  elyra/elyra_app.py
  elyra/metadata/manager.py
  elyra/metadata/metadata_app.py
  elyra/metadata/schema.py
  elyra/metadata/schemas/component-registry.json
  elyra/metadata/schemas/local-directory-catalog.json
  elyra/metadata/schemas/local-file-catalog.json
  elyra/metadata/schemas/url-catalog.json
  elyra/metadata/schemaspaces.py
  elyra/metadata/schemasproviders.py
  elyra/pipeline/airflow/processor_airflow.py
  elyra/pipeline/component_catalog.py
  elyra/pipeline/component_metadata.py
  elyra/pipeline/handlers.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/local/processor_local.py
  elyra/pipeline/processor.py
  elyra/pipeline/validation.py
  elyra/tests/cli/test_pipeline_app.py
  elyra/tests/metadata/test_metadata_app.py
  elyra/tests/pipeline/airflow/test_component_parser_airflow.py
  elyra/tests/pipeline/kfp/test_component_parser_kfp.py
  elyra/tests/pipeline/kfp/test_processor_kfp.py
  etc/config/metadata/component-catalogs/elyra-airflow-filesystem-preconfig.json
  etc/config/metadata/component-catalogs/elyra-airflow-url-preconfig.json
  etc/config/metadata/component-catalogs/elyra-kfp-directory-preconfig.json
  etc/config/metadata/component-catalogs/elyra-kfp-url-preconfig.json
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/pipeline-editor/src/PipelineService.tsx
  packages/pipeline-editor/src/index.ts
  setup.py
Labels: impact:needs doc updates

#2308 Fix documentation builds
  docs/requirements.txt
Labels: component:build, external:Upstream

#2302 Update components section with migration instructions
  docs/source/user_guide/pipeline-components.md
Labels: area:documentation

#2306 Fix incorrect reference to upstream operator when duplicate exists
  elyra/pipeline/airflow/processor_airflow.py
  elyra/tests/pipeline/airflow/test_processor_airflow.py
  elyra/tests/pipeline/resources/validation_pipelines/aa_operator_same_name.pipeline
  yarn.lock
Labels: kind:bug, component:pipeline-runtime

#2310 Update hybrid runtime support topic in overview doc
  docs/source/getting_started/overview.md
Labels: area:documentation

#2315 Add packaging section to installation documentation
  docs/source/getting_started/installation.md
Labels: area:documentation

#2236 Update pipeline styles
  packages/pipeline-editor/src/theme.tsx
Labels: external:Upstream
