Repository elyra-ai/elyra, pull requests merged in 2021-04, with the labels that each got.

#1508 Fix default return value for node when using submit button
  elyra/pipeline/parser.py
Labels: priority:high

#1507 Add command line interface topic to user guide
  docs/source/index.rst
  docs/source/user_guide/command-line-interface.md
Labels: area:documentation, component: CLI-tools

#1552 Update project MANIFEST.in with missing files
  MANIFEST.in
Labels: component:build

#1561 Add link to Kubeflow Notebook Server configuration recipe
  docs/source/getting_started/installation.md
Labels: area:documentation

#1604 Fix links to pipelines documentation topic
  docs/source/user_guide/command-line-interface.md
Labels: area:documentation
