Repository elyra-ai/elyra, pull requests merged in 2021-12, with the labels that each got.

#2316 support operators with type hints
  elyra/pipeline/airflow/component_parser_airflow.py
  elyra/pipeline/component.py
  elyra/templates/components/canvas_properties_template.jinja2
  elyra/tests/pipeline/airflow/test_component_parser_airflow.py
  elyra/tests/pipeline/kfp/test_component_parser_kfp.py
  elyra/tests/pipeline/resources/components/airflow_test_operator_type_hints.py
  setup.py
Labels: platform: pipeline-Airflow

#2345 Add 'resources' topic to 'getting started' documentation
  docs/source/getting_started/published-resources.md
  docs/source/getting_started/tutorials.md
  docs/source/index.rst
Labels: area:documentation

#2353 Fix typo in runtime configuration topic
  docs/source/user_guide/runtime-conf.md
Labels: kind:bug, area:documentation

#2351 Add Elyra 3.3 blog post to resources topic
  docs/source/getting_started/published-resources.md
Labels: area:documentation

#2358 Fix KUBERNETES_SERVICE_ACCOUNT_TOKEN auth
  elyra/pipeline/kfp/kfp_authentication.py
  elyra/pipeline/kfp/processor_kfp.py
  setup.py
Labels: kind:bug, platform: pipeline-Kubeflow

#2356 Enforce authentication type constraints in KFP RTCs
  elyra/metadata/schemas/kfp.json
  elyra/pipeline/kfp/kfp_metadata.py
Labels: component:metadata, platform: pipeline-Kubeflow

#2350 Allow Kubeflow node inputValues to consume outputPath outputs
  elyra/pipeline/airflow/component_parser_airflow.py
  elyra/pipeline/component.py
  elyra/pipeline/kfp/component_parser_kfp.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/pipeline.py
  elyra/pipeline/validation.py
  elyra/templates/components/canvas_properties_template.jinja2
  elyra/tests/cli/resources/kfp_3_node_custom.pipeline
  elyra/tests/pipeline/kfp/test_component_parser_kfp.py
  elyra/tests/pipeline/resources/components/kfp_test_operator.yaml
  elyra/tests/pipeline/resources/validation_pipelines/aa_invalid_node_op.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/aa_parent_node_missing_xcom.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_basic_filepath_check.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_basic_pipeline_only_notebook.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_basic_pipeline_with_scripts.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_double_cycle.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_invalid_node_property_dependency_file_path.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_invalid_node_property_hardware_resources.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_invalid_node_property_image_name.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_invalid_node_property_structure.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_single_cycle.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/generic_singleton.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_inputpath_parameter.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_invalid_inputpath_missing_connection.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_invalid_inputpath_parameter.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_invalid_node_property_in_component.pipeline
  elyra/tests/pipeline/resources/validation_pipelines/kf_supernode_valid.pipeline
  packages/pipeline-editor/package.json
  tests/assets/helloworld.pipeline
  tests/assets/invalid.pipeline
  tests/assets/pipelines/producer-consumer.pipeline
  tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
  tests/snapshots/pipeline-editor-tests/matches-empty-pipeline-snapshot.1.snap
  tests/snapshots/pipeline-editor-tests/matches-simple-pipeline-snapshot.1.snap
  yarn.lock
Labels: impact:needs doc updates, internal:upstream

#2368 Fix incorrect syntax in kubeflow image layer
  etc/docker/kubeflow/Dockerfile
Labels: kind:bug, component:build
