Repository elyra-ai/elyra, pull requests merged in 2022-07, with the labels that each got.

#2817 Remove final instance of `BashOperator` from tests
  conftest.py
  elyra/tests/pipeline/airflow/test_component_parser_airflow.py
Labels: kind:bug, component:test

#2819 Optionally search for operators in airflow.contrib.operators package
  elyra/pipeline/airflow/component_parser_airflow.py
  elyra/pipeline/airflow/package_catalog_connector/README.md
  elyra/pipeline/airflow/package_catalog_connector/airflow-package-catalog.json
  elyra/pipeline/airflow/package_catalog_connector/airflow_package_catalog_connector.py
Labels: kind:bug, component:catalog connectors

#2831 Update typing extensions dependency version cap
  setup.py
Labels: component:build

#2829 Add support for schema validators
  docs/source/developer_guide/metadata.md
  elyra/metadata/manager.py
  elyra/metadata/schema.py
  elyra/tests/metadata/test_metadata.py
  elyra/tests/metadata/test_metadata_app.py
Labels: kind:enhancement, component:metadata, area:back-end

#2845 Fix container image build issues for official releases
  etc/docker/elyra/Dockerfile
  etc/docker/kubeflow/Dockerfile
Labels: kind:bug, component:build

#2853 Fix doc requirements to address build issue
  docs/requirements.txt
Labels: area:documentation, kind:CI

#2808 added dockerfile and requirements file
  etc/docker/elyra_development/Dockerfile
  etc/docker/elyra_development/requirements.yml
Labels: component:build

#2860 Fix invalid URL in extension descriptions
  create-release.py
Labels: kind:bug, component:build
