Repository elyra-ai/elyra, pull requests merged in 2022-04, with the labels that each got.

#2623 [HOTFIX] Fix missing f string typo in operator
  elyra/kfp/operator.py
Labels: kind:bug

#2628 Improve custom container image build instructions
  etc/docker/elyra/README.md
  etc/docker/kubeflow/README.md
Labels: kind:bug

#2629 fix gitlab port bug
  elyra/util/gitlab.py
Labels: kind:bug, component:pipeline-runtime

#2630 Abort generic component processing when prereq download fails
  elyra/airflow/operator.py
  elyra/kfp/operator.py
Labels: kind:bug, component:pipeline-runtime

#2633 Pipeline CLI: Add support for static text spinner
  elyra/cli/pipeline_app.py
  elyra/cli/pipeline_app_utils.py
Labels: kind:bug, component:cli-tools

#2631 Add support for dedicated public KFP endpoint
  docs/source/user_guide/runtime-conf.md
  elyra/metadata/schemas/kfp.json
  elyra/pipeline/kfp/processor_kfp.py
  packages/pipeline-editor/src/RuntimesWidget.tsx
Labels: kind:enhancement, component:pipeline-runtime, platform: pipeline-Kubeflow

#2643 Tolerate editable packages in bootstrapper package install
  elyra/airflow/bootstrapper.py
  elyra/kfp/bootstrapper.py
  elyra/tests/kfp/resources/test-requirements-current.txt
  elyra/tests/kfp/test_bootstrapper.py
Labels: kind:bug

#2645 Improve argument handling in elyra-metadata
  elyra/metadata/metadata_app_utils.py
  elyra/tests/metadata/test_metadata_app.py
  elyra/tests/metadata/test_utils.py
Labels: kind:bug, component:cli-tools

#2646 Fix KFP component without inputs compilation bug
  elyra/pipeline/component_catalog.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/tests/pipeline/kfp/test_component_parser_kfp.py
  elyra/tests/pipeline/kfp/test_processor_kfp.py
Labels: kind:bug, component:pipeline-runtime, platform: pipeline-Kubeflow

#2651 Improve documentation topics that reference the CLI
  docs/source/recipes/deploying-kubeflow-locally-for-dev.md
  docs/source/user_guide/code-snippets.md
  docs/source/user_guide/command-line-interface.md
  docs/source/user_guide/pipeline-components.md
  docs/source/user_guide/runtime-conf.md
  docs/source/user_guide/runtime-image-conf.md
Labels: area:documentation

#2650 Support emissary as workflow executor for KFP with Argo
  docs/source/user_guide/best-practices-custom-pipeline-components.md
  elyra/pipeline/kfp/component_parser_kfp.py
Labels: kind:enhancement, platform: pipeline-Kubeflow

#2654 Remove use of legacy resolver in builds and documentation
  Makefile
  README.md
  binder/postBuild
  docs/source/getting_started/installation.md
  etc/docker/elyra/Dockerfile
  etc/docker/kubeflow/Dockerfile
Labels: area:documentation, component:build

#2661 Update repository README to include a link to releases page
  README.md
Labels: area:documentation

#2660 Publish latest-tagged images when building releases
  Makefile
Labels: component:build, component:docker

#2658 Update documentation URLs in schema definitions
  create-release.py
  elyra/metadata/schemas/local-directory-catalog.json
  elyra/metadata/schemas/local-file-catalog.json
  elyra/metadata/schemas/url-catalog.json
Labels: kind:bug

#2656 Add support for runtime image and env vars in pipeline default properties
  elyra/api/elyra.yaml
  elyra/elyra_app.py
  elyra/pipeline/handlers.py
  elyra/pipeline/kfp/component_parser_kfp.py
  elyra/pipeline/pipeline.py
  elyra/pipeline/pipeline_constants.py
  elyra/pipeline/pipeline_definition.py
  elyra/templates/components/generic_properties_template.jinja2
  elyra/templates/pipeline/pipeline_properties_template.jinja2
  elyra/tests/pipeline/resources/properties.json
  elyra/tests/pipeline/resources/sample_pipelines/pipeline_valid_with_pipeline_default.json
  elyra/tests/pipeline/test_handlers.py
  elyra/tests/pipeline/test_pipeline_definition.py
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/pipeline-editor/src/PipelineService.tsx
  packages/pipeline-editor/src/pipeline-hooks.ts
  packages/pipeline-editor/src/pipelineProperties.ts
  packages/pipeline-editor/style/index.css
Labels: kind:enhancement, component:pipeline-editor, component:pipeline-runtime, impact:needs doc updates

#2668 Add documentation for pipeline default properties
  docs/source/images/user_guide/best-practices-file-based-nodes/default-runtime-image.png
  docs/source/images/user_guide/best-practices-file-based-nodes/vpe-node-env-vars.png
  docs/source/images/user_guide/best-practices-file-based-nodes/vpe-node-input-files.png
  docs/source/images/user_guide/best-practices-file-based-nodes/vpe-node-output-files.png
  docs/source/images/user_guide/pipelines/pipeline-properties.png
  docs/source/user_guide/best-practices-file-based-nodes.md
  docs/source/user_guide/pipelines.md
Labels: area:documentation

#2677 Remove secret from airflow helm values
  etc/kubernetes/airflow/helm/values.yaml
Labels: platform: pipeline-Airflow

#2673 Update development dockerfiles to use prebuilt extensions
  Makefile
  docs/source/developer_guide/development-workflow.md
  etc/docker/elyra/Dockerfile
  etc/docker/elyra/Dockerfile.dev
  etc/docker/kubeflow/Dockerfile
  etc/docker/kubeflow/Dockerfile.dev
Labels: component:build

#2675 Support use of mounted volumes in Kubeflow Pipelines runtime
  elyra/kfp/operator.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/pipeline_constants.py
  elyra/pipeline/processor.py
  elyra/templates/components/generic_properties_template.jinja2
  elyra/templates/pipeline/pipeline_properties_template.jinja2
  elyra/tests/pipeline/resources/properties.json
  elyra/tests/pipeline/test_handlers.py
  elyra/tests/util/test_kubernetes.py
  elyra/util/kubernetes.py
  tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
  tests/snapshots/pipeline-editor-tests/matches-simple-pipeline-snapshot.1.snap
Labels: kind:enhancement, component:pipeline-editor, component:pipeline-runtime, platform: pipeline-Kubeflow, impact:needs doc updates

#2669 Add support for storing pipeline parameters and COS prefixes
  elyra/airflow/bootstrapper.py
  elyra/airflow/operator.py
  elyra/kfp/bootstrapper.py
  elyra/kfp/operator.py
  elyra/pipeline/airflow/processor_airflow.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/parser.py
  elyra/pipeline/pipeline.py
  elyra/pipeline/pipeline_constants.py
  elyra/pipeline/pipeline_definition.py
  elyra/pipeline/processor.py
  elyra/templates/pipeline/pipeline_properties_template.jinja2
  elyra/tests/airflow/test_airflow_operator.py
  elyra/tests/kfp/test_bootstrapper.py
  elyra/tests/pipeline/airflow/test_processor_airflow.py
  elyra/tests/pipeline/test_handlers.py
  elyra/tests/util/test_cos.py
  elyra/util/cos.py
Labels: kind:enhancement, component:pipeline-editor, platform: pipeline-Kubeflow, impact:needs doc updates

#2581 Add support for metadata import in the CLI
  docs/source/user_guide/code-snippets.md
  docs/source/user_guide/command-line-interface.md
  docs/source/user_guide/pipeline-components.md
  docs/source/user_guide/runtime-conf.md
  docs/source/user_guide/runtime-image-conf.md
  elyra/metadata/metadata_app.py
  elyra/tests/metadata/test_metadata_app.py
Labels: kind:enhancement, component:cli-tools

#2680 Support use of mounted volumes in airflow runtime
  elyra/pipeline/airflow/processor_airflow.py
  elyra/templates/airflow/airflow_template.jinja2
  elyra/tests/pipeline/resources/sample_pipelines/pipeline_dependency_complex.json
  elyra/tests/pipeline/test_processor_base.py
Labels: kind:enhancement, component:pipeline-editor, component:pipeline-runtime, platform: pipeline-Airflow

#2682 Add pipeline properties documentation to pipelines topic
  docs/source/images/user_guide/pipelines/generic-node-artifacts-custom-layout.png
  docs/source/images/user_guide/pipelines/node-artifacts-on-object-storage.png
  docs/source/images/user_guide/pipelines/pipeline-properties.png
  docs/source/user_guide/pipeline-components.md
  docs/source/user_guide/pipelines.md
Labels: area:documentation, kind:enhancement

#2690 Fix broken links to documentation
  elyra/cli/pipeline_app.py
  packages/pipeline-editor/src/EmptyPipelineContent.tsx
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
Labels: kind:bug, area:documentation

#2688 Conditionally render object storage information after pipeline submission
  elyra/cli/pipeline_app.py
  elyra/pipeline/airflow/processor_airflow.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/pipeline.py
  packages/pipeline-editor/src/PipelineService.tsx
Labels: component:pipeline-editor, component:cli-tools, platform: pipeline-Kubeflow, platform: pipeline-Airflow
