Repository elyra-ai/elyra, pull requests merged in 2022-08, with the labels that each got.

#2839 Update user guide to enable elyra[all] install on zsh
  docs/source/getting_started/installation.md
  docs/source/getting_started/troubleshooting.md
  docs/source/index.rst
  docs/source/user_guide/pipeline-components.md
Labels: kind:bug, area:documentation

#2850 Add Scala editor
  Makefile
  README.md
  create-release.py
  docs/source/developer_guide/release.md
  docs/source/getting_started/installation.md
  docs/source/images/launcher-python-editor.png
  docs/source/images/launcher-r-editor.png
  docs/source/images/launcher-scala-editor.png
  docs/source/images/script-editor-components.png
  docs/source/user_guide/enhanced-script-support.md
  packages/scala-editor/package.json
  packages/scala-editor/src/ScalaEditor.tsx
  packages/scala-editor/src/index.ts
  packages/scala-editor/style/index.css
  packages/scala-editor/tsconfig.json
  packages/ui-components/src/icons.tsx
  packages/ui-components/style/icons/scala-logo.svg
Labels: kind:enhancement, component:scala-editor

#2865 Fix Airflow Operator execution bugs in handling of Elyra-owned properties
  elyra/pipeline/pipeline.py
  elyra/pipeline/pipeline_definition.py
  elyra/tests/pipeline/airflow/test_processor_airflow.py
  elyra/tests/pipeline/resources/sample_pipelines/pipeline_valid_with_pipeline_default.json
  elyra/tests/pipeline/resources/sample_pipelines/pipeline_with_airflow_components.json
  elyra/tests/pipeline/test_pipeline_definition.py
  elyra/tests/pipeline/test_pipeline_parser.py
Labels: kind:bug, component:pipeline-runtime

#2871 Improve 'Running Elyra in an air-gapped environment' documentation topic
  docs/source/recipes/running-elyra-in-air-gapped-environment.md
Labels: area:documentation

#2868 Add support for Kubernetes annotations
  docs/source/user_guide/pipelines.md
  elyra/kfp/operator.py
  elyra/pipeline/airflow/processor_airflow.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/pipeline.py
  elyra/pipeline/pipeline_constants.py
  elyra/pipeline/pipeline_definition.py
  elyra/pipeline/validation.py
  elyra/templates/airflow/airflow_template.jinja2
  elyra/templates/components/canvas_properties_template.jinja2
  elyra/templates/components/generic_properties_template.jinja2
  elyra/templates/pipeline/pipeline_properties_template.jinja2
  elyra/tests/pipeline/airflow/test_component_parser_airflow.py
  elyra/tests/pipeline/kfp/test_component_parser_kfp.py
  elyra/tests/pipeline/resources/properties.json
  elyra/tests/pipeline/test_handlers.py
  elyra/tests/pipeline/test_validation.py
  elyra/util/kubernetes.py
  tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
  tests/snapshots/pipeline-editor-tests/matches-simple-pipeline-snapshot.1.snap
Labels: kind:enhancement, component:pipeline-editor, component:pipeline-runtime

#2835 Improve repository README
  README.md
Labels: area:documentation

#2832 Dev workflow documentation updates
  docs/source/developer_guide/development-workflow.md
Labels: area:documentation, mentoring:RCOS

#2873 Add support for 'file' URI scheme to URL-based connectors
  docs/source/user_guide/pipeline-components.md
  elyra/pipeline/airflow/package_catalog_connector/airflow_package_catalog_connector.py
  elyra/pipeline/airflow/provider_package_catalog_connector/airflow_provider_package_catalog_connector.py
  elyra/pipeline/catalog_connector.py
  elyra/tests/pipeline/airflow/test_airflow_package_connector.py
  elyra/tests/pipeline/airflow/test_airflow_provider_package_connector.py
  elyra/tests/pipeline/test_catalog_connector.py
  elyra/tests/util/test_url.py
  elyra/util/url.py
Labels: kind:enhancement, component:catalog connectors

#2848 Add support for Kubernetes tolerations
  docs/source/user_guide/pipelines.md
  elyra/kfp/operator.py
  elyra/pipeline/airflow/processor_airflow.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/pipeline.py
  elyra/pipeline/pipeline_constants.py
  elyra/pipeline/pipeline_definition.py
  elyra/pipeline/processor.py
  elyra/pipeline/validation.py
  elyra/templates/airflow/airflow_template.jinja2
  elyra/templates/components/canvas_properties_template.jinja2
  elyra/templates/components/generic_properties_template.jinja2
  elyra/templates/pipeline/pipeline_properties_template.jinja2
  elyra/tests/pipeline/airflow/test_component_parser_airflow.py
  elyra/tests/pipeline/kfp/test_component_parser_kfp.py
  elyra/tests/pipeline/resources/properties.json
  elyra/tests/pipeline/test_handlers.py
  elyra/tests/pipeline/test_validation.py
  tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
  tests/snapshots/pipeline-editor-tests/matches-simple-pipeline-snapshot.1.snap
Labels: kind:enhancement, component:pipeline-editor, component:pipeline-runtime

#2876 Add export and validation handler tests
  elyra/pipeline/handlers.py
  elyra/tests/pipeline/test_handlers.py
Labels: component:test, mentoring:RCOS

#2879 Makefile: Add capability to validate individual runtime images
  Makefile
Labels: kind:enhancement, component:build

#2883 Fix invalid variable names in error messages
  elyra/util/cos.py
Labels: kind:bug

#2857 Add "what's new" tile to launcher
  create-release.py
  packages/theme/src/index.ts
  packages/ui-components/src/icons.tsx
  packages/ui-components/style/icons/whats-new.svg
  tests/integration/launcher.ts
Labels: kind:enhancement, area:front-end, mentoring:RCOS

#2884 Bump kfp-tekton dependency to 1.3.0
  setup.py
Labels: platform: pipeline-Kubeflow, dependencies

#2843 Fix release script and instructions
  Makefile
  create-release.py
  docs/source/developer_guide/release.md
  etc/docker/elyra/Dockerfile
  etc/docker/kubeflow/Dockerfile
Labels: kind:bug, area:documentation, component:build

#2882 Add image verification steps to 'Creating a custom runtime container image' documentation
  docs/source/recipes/creating-a-custom-runtime-image.md
Labels: area:documentation

#2885 Fix linting errors in server code
  elyra/tests/pipeline/test_handlers.py
Labels: kind:bug, component:build

#2878 Improve JSON output of 'elyra-pipeline describe' command
  elyra/cli/pipeline_app.py
  elyra/tests/cli/resources/pipelines/kfp_3_node_custom.pipeline
  elyra/tests/cli/test_pipeline_app.py
Labels: component:cli-tools

#2887 Add support for COS public endpoint to Kubeflow Pipelines runtime config
  docs/source/user_guide/runtime-conf.md
  elyra/metadata/schemas/kfp.json
  elyra/pipeline/kfp/processor_kfp.py
  packages/pipeline-editor/src/RuntimesWidget.tsx
  tests/support/commands.ts
Labels: kind:enhancement, component:metadata-editor, platform: pipeline-Kubeflow

#2890 Add support for COS public endpoint to Airflow runtime config
  elyra/metadata/schemas/airflow.json
  elyra/pipeline/airflow/processor_airflow.py
  packages/pipeline-editor/src/RuntimesWidget.tsx
Labels: kind:enhancement, component:metadata-editor, platform: pipeline-Airflow

#2889 Update documentation for elyra development image
  etc/docker/elyra_development/Dockerfile
  etc/docker/elyra_development/README.md
Labels: area:documentation

#2895 Address SVG rendering issues
  packages/ui-components/style/icons/pipeline-components.svg
Labels: kind:bug, component:metadata-editor

#2896 Node package security updates
  package.json
  packages/script-editor/package.json
  packages/services/package.json
  yarn.lock
Labels: component:build, area:front-end

#2900 simplify handlers test
  elyra/tests/pipeline/resources/generic_properties_template.jinja2
  elyra/tests/pipeline/resources/properties.json
  elyra/tests/pipeline/test_handlers.py
Labels: component:test

#2905 Support disabling node output caching for custom KFP components
  docs/source/user_guide/pipelines.md
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/pipeline.py
  elyra/pipeline/pipeline_constants.py
  elyra/templates/components/canvas_properties_template.jinja2
  elyra/templates/pipeline/pipeline_properties_template.jinja2
  elyra/tests/pipeline/airflow/test_component_parser_airflow.py
  elyra/tests/pipeline/kfp/test_component_parser_kfp.py
  elyra/tests/pipeline/test_handlers.py
Labels: kind:enhancement, component:pipeline-editor, platform: pipeline-Kubeflow

#2909 Improve content of the pipelines documentation topic
  docs/source/images/user_guide/pipelines/connect-nodes.gif
  docs/source/images/user_guide/pipelines/node-graph-example.png
  docs/source/images/user_guide/pipelines/open-pipeline-properties.gif
  docs/source/images/user_guide/pipelines/pipeline-properties.png
  docs/source/images/user_guide/pipelines/shortcut-to-pipeline-editor-settings.png
  docs/source/user_guide/pipelines.md
Labels: area:documentation

#2913 Move CLI component cache build to occur before pre-processing
  conftest.py
  elyra/cli/pipeline_app.py
  elyra/tests/cli/test_pipeline_app.py
Labels: kind:bug, component:cli-tools
