Repository elyra-ai/elyra, pull requests merged in 2022-05, with the labels that each got.

#2693 Add 'Elyra JupyterLab interface' topic to user guide
  create-release.py
  docs/source/images/user_guide/jupyterlab-interface/code-snippets-sidebar.png
  docs/source/images/user_guide/jupyterlab-interface/component-catalogs-sidebar.png
  docs/source/images/user_guide/jupyterlab-interface/jupyterlab-sidebars.png
  docs/source/images/user_guide/jupyterlab-interface/launcher.png
  docs/source/images/user_guide/jupyterlab-interface/runtime-configurations-sidebar.png
  docs/source/images/user_guide/jupyterlab-interface/runtime-images-sidebar.png
  docs/source/images/user_guide/jupyterlab-interface/visual-pipeline-editor.png
  docs/source/index.rst
  docs/source/user_guide/jupyterlab-interface.md
Labels: area:documentation, kind:enhancement

#2632 Update to JupyterLab 3.4
  docs/source/developer_guide/contributing.md
  docs/source/getting_started/installation.md
  package.json
  packages/code-snippet/package.json
  packages/code-viewer/package.json
  packages/metadata-common/package.json
  packages/metadata/package.json
  packages/pipeline-editor/package.json
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/python-editor/package.json
  packages/r-editor/package.json
  packages/script-editor/package.json
  packages/services/package.json
  packages/theme/package.json
  packages/theme/src/index.ts
  packages/theme/src/launcher.tsx
  packages/ui-components/package.json
  setup.py
  yarn.lock
Labels: impact:do-not-merge, external:jupyterlab 3.4

#2703 Fix incorrect regex search in release script
  create-release.py
  elyra/_version.py
Labels: component:build

#2707 Add link to new blog post to "published resources" documentation
  docs/source/getting_started/published-resources.md
Labels: area:documentation

#2708 Update elyra individual extension package descriptions
  create-release.py
  etc/templates/setup.py
Labels: component:build

#2710 Remove dependency on ipython_genutils
  elyra/metadata/metadata.py
Labels: component:application-utils, area:back-end

#2714 Update changelog header
  create-release.py
  docs/source/getting_started/changelog.md
Labels: area:documentation, component:build

#2705 Simplify R and Python icon svgs
  LICENSE
  packages/ui-components/style/icons/py-logo.svg
  packages/ui-components/style/icons/r-logo.svg
  tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
Labels: kind:bug, status:Work in Progress

#2538 Metadata tag whitespace proposed solution
  elyra/metadata/schemas/airflow.json
  elyra/metadata/schemas/code-snippet.json
  elyra/metadata/schemas/kfp.json
  elyra/metadata/schemas/metadata-test.json
  elyra/metadata/schemas/runtime-image.json
  elyra/tests/metadata/test_metadata.py
Labels: component:metadata, area:back-end

#2720 Improve github action workflow
  .github/workflows/build.yml
Labels: kind:CI

#2575 Update node packages to fix security vulnerabilities
  package.json
  packages/pipeline-editor/package.json
  tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
  tests/snapshots/pipeline-editor-tests/matches-empty-pipeline-snapshot.1.snap
  tests/snapshots/pipeline-editor-tests/matches-simple-pipeline-snapshot.1.snap
  yarn.lock
Labels: component:build

#2729 Remove tensorflow 1.x sample runtime images
  docs/source/user_guide/command-line-interface.md
  etc/config/metadata/runtime-images/tensorflow_gpu_py3.json
  etc/config/metadata/runtime-images/tensorflow_py3.json
  etc/docker/README.md
  etc/docker/tensorflow/1.15.5-gpu-py3/Dockerfile
  etc/docker/tensorflow/1.15.5-py3/Dockerfile
  etc/docker/tensorflow/README.md
Labels: component:metadata, component:runtime-image

#2709 Develop Elyra against the Jupyterlab source repo
  .github/workflows/build.yml
  Makefile
  build_requirements.txt
  docs/source/developer_guide/development-workflow.md
  etc/config/settings/page_config.json
  etc/scripts/clean-jupyterlab.sh
  packages/code-snippet/package.json
  packages/code-viewer/package.json
  packages/metadata-common/src/MetadataEditor.tsx
  packages/metadata/package.json
  packages/pipeline-editor/package.json
  packages/python-editor/package.json
  packages/r-editor/package.json
  packages/theme/package.json
  setup.py
  tsconfig.base.json
Labels: area:documentation, component:build

#2728 Prepend baseUrl to icon source
  packages/pipeline-editor/package.json
  packages/pipeline-editor/src/pipeline-hooks.ts
Labels: kind:bug, component:pipeline-editor

#2732 Bump NodeJS version requirement to v16 or higher
  README.md
  create-release.py
  docs/source/developer_guide/development-workflow.md
  docs/source/getting_started/installation.md
Labels: area:documentation

#2734 Fix pipeline submit button reload bug
  packages/ui-components/src/FormDialog.tsx
Labels: kind:bug, component:pipeline-editor

#2731 Add elyra documentation link in elyra-metadata help
  create-release.py
  elyra/metadata/metadata_app_utils.py
Labels: component:cli-tools

#2727 Update generic component operator to support python 3.7
  Makefile
  elyra/airflow/bootstrapper.py
  elyra/airflow/operator.py
  elyra/kfp/bootstrapper.py
  elyra/kfp/operator.py
  etc/generic/requirements-elyra-py37.txt
  etc/generic/requirements-elyra.txt
Labels: component:pipeline-runtime

#2698 Improve pipeline validation
  elyra/templates/components/generic_properties_template.jinja2
  elyra/tests/pipeline/resources/properties.json
  packages/pipeline-editor/package.json
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/pipeline-editor/style/index.css
  yarn.lock
Labels: component:pipeline-editor, impact:requires-pipeline-editor-release

#2715 Add backend support for Kubernetes secrets environment variables
  docs/source/user_guide/best-practices-file-based-nodes.md
  docs/source/user_guide/pipelines.md
  elyra/kfp/operator.py
  elyra/pipeline/airflow/processor_airflow.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/pipeline.py
  elyra/pipeline/pipeline_constants.py
  elyra/pipeline/pipeline_definition.py
  elyra/pipeline/processor.py
  elyra/pipeline/validation.py
  elyra/templates/airflow/airflow_template.jinja2
  elyra/templates/components/generic_properties_template.jinja2
  elyra/templates/pipeline/pipeline_properties_template.jinja2
  elyra/tests/pipeline/resources/properties.json
  elyra/tests/pipeline/test_handlers.py
  elyra/tests/pipeline/test_pipeline_definition.py
  elyra/tests/pipeline/test_processor_base.py
  elyra/tests/pipeline/test_validation.py
  elyra/util/kubernetes.py
  tests/snapshots/pipeline-editor-tests/matches-complex-pipeline-snapshot.1.snap
  tests/snapshots/pipeline-editor-tests/matches-simple-pipeline-snapshot.1.snap
Labels: kind:enhancement

#2722 Elyra pipeline describe enhancements
  elyra/cli/pipeline_app.py
  elyra/tests/cli/resources/pipelines/kf_inputpath_parameter.pipeline
  elyra/tests/cli/resources/pipelines/kfp_3_node_custom.pipeline
  elyra/tests/cli/resources/pipelines/pipeline_with_many_mount.pipeline
  elyra/tests/cli/resources/pipelines/pipeline_with_many_runtime_image.pipeline
  elyra/tests/cli/resources/pipelines/pipeline_with_notebook.pipeline
  elyra/tests/cli/resources/pipelines/pipeline_with_notebook_and_script.pipeline
  elyra/tests/cli/resources/pipelines/pipeline_with_one_mount.pipeline
  elyra/tests/cli/resources/pipelines/pipeline_with_one_runtime_image.pipeline
  elyra/tests/cli/resources/pipelines/pipeline_with_script.pipeline
  elyra/tests/cli/resources/pipelines/pipeline_with_zero_mount.pipeline
  elyra/tests/cli/resources/pipelines/pipeline_with_zero_runtime_image.pipeline
  elyra/tests/cli/test_pipeline_app.py
Labels: kind:enhancement, component:cli-tools

#2744 Add 'Running Elyra in an air gapped environment' topic to documentation
  create-release.py
  docs/source/images/recipes/running-elyra-in-air-gapped-environment/installation-dependencies.png
  docs/source/images/recipes/running-elyra-in-air-gapped-environment/runtime-dependencies.png
  docs/source/index.rst
  docs/source/recipes/running-elyra-in-air-gapped-environment.md
Labels: area:documentation, kind:enhancement

#2743 Fix metadata dropdown style in dark mode
  packages/metadata-common/style/index.css
Labels: kind:bug, component:metadata-editor
