Repository elyra-ai/elyra, pull requests merged in 2022-02, with the labels that each got.

#2450 Add link to Apache Airflow custom components tutorial to 'Getting Started' guide
  docs/source/getting_started/tutorials.md
Labels: area:documentation, kind:enhancement

#2437 Add airflow package catalog connector
  MANIFEST.in
  elyra/pipeline/airflow/package_catalog_connector/README.md
  elyra/pipeline/airflow/package_catalog_connector/__init__.py
  elyra/pipeline/airflow/package_catalog_connector/airflow-package-catalog.json
  elyra/pipeline/airflow/package_catalog_connector/airflow_package_catalog_connector.py
  elyra/pipeline/airflow/package_catalog_connector/airflow_package_schema_provider.py
  setup.py
  tests/support/commands.ts
Labels: area:documentation, kind:enhancement, platform: pipeline-Airflow

#2438 Add Airflow provider package catalog connector
  MANIFEST.in
  elyra/pipeline/airflow/provider_package_catalog_connector/README.md
  elyra/pipeline/airflow/provider_package_catalog_connector/__init__.py
  elyra/pipeline/airflow/provider_package_catalog_connector/airflow-provider-package-catalog.json
  elyra/pipeline/airflow/provider_package_catalog_connector/airflow_provider_package_catalog_connector.py
  elyra/pipeline/airflow/provider_package_catalog_connector/airflow_provider_package_schema_provider.py
  setup.py
Labels: area:documentation, kind:enhancement, platform: pipeline-Airflow

#2457 Update built-in connector reference in 'Pipeline Components' documentation
  docs/source/user_guide/pipeline-components.md
Labels: area:documentation

#2465 Restore tag variable, update release script
  create-release.py
  etc/docker/kubeflow/Dockerfile
Labels: kind:bug, component:build

#2473 Fix default value rendering in properties template for KFP 'inputvalue' types
  elyra/templates/components/canvas_properties_template.jinja2
  elyra/tests/pipeline/kfp/test_component_parser_kfp.py
Labels: kind:bug

#2479 Deprecate python 3.6 usage and include 3.10 in testing
  .github/workflows/build.yml
  README.md
  setup.py
Labels: component:build

#2486 Add a link to most recent blog to the documentation
  docs/source/getting_started/published-resources.md
Labels: area:documentation

#2468 Replace invalid characters in airflow parent node references
  elyra/pipeline/airflow/processor_airflow.py
  elyra/pipeline/pipeline.py
  elyra/tests/pipeline/airflow/test_processor_airflow.py
Labels: kind:bug, platform: pipeline-Airflow

#2483 Create git release configuration configuration file
  .github/release.yml
Labels: component:build

#2485 Document how to configure custom Airflow components for use in pipelines
  docs/source/images/user_guide/best-practices-custom-pipeline-components/config-error-message.png
  docs/source/user_guide/best-practices-custom-pipeline-components.md
  docs/source/user_guide/pipeline-components.md
Labels: area:documentation

#2478 Add support for custom requirements in Elyra container image build
  Makefile
  etc/docker/elyra/Dockerfile
  etc/docker/elyra/Dockerfile.dev
  etc/docker/elyra/README.md
  etc/docker/elyra/requirements.txt
Labels: kind:enhancement, component:build

#2487 Update dependencies to avoid security vulnerabilities
  elyra/tests/kfp/resources/test-bad-requirements-elyra.txt
  elyra/tests/kfp/resources/test-requirements-elyra.txt
  etc/generic/requirements-elyra.txt
  setup.py
Labels: component:build, dependencies

#2490 Fix typo in git release configuration configuration file
  .github/release.yml
Labels: component:build, ignore-for-release

#2493 Bump version requirement for nbformat, ipython, and traitlets
  etc/generic/requirements-elyra.txt
Labels: kind:bug, component:pipeline-runtime

#2480 Bump kfp-tekton dependency
  setup.py
Labels: component:build

#2448 Add support for cli metadata export
  docs/source/user_guide/code-snippets.md
  docs/source/user_guide/command-line-interface.md
  docs/source/user_guide/pipeline-components.md
  docs/source/user_guide/runtime-conf.md
  docs/source/user_guide/runtime-image-conf.md
  elyra/metadata/manager.py
  elyra/metadata/metadata_app.py
  elyra/tests/metadata/test_metadata.py
  elyra/tests/metadata/test_metadata_app.py
Labels: kind:enhancement, component:cli-tools

#2496 Update examples for verification step and first issue label
  CONTRIBUTING.md
  README.md
  docs/source/getting_started/installation.md
Labels: area:documentation

#2447 Update build to use prebuilt extensions
  .github/workflows/build.yml
  Makefile
  README.md
  binder/postBuild
  build_requirements.txt
  create-release.py
  docs/source/developer_guide/development-workflow.md
  docs/source/developer_guide/troubleshooting.md
  docs/source/getting_started/installation.md
  etc/docker/elyra/Dockerfile
  etc/docker/kubeflow/Dockerfile
  etc/scripts/clean-jupyterlab.sh
  lint_requirements.txt
  package.json
  packages/code-snippet/package.json
  packages/metadata-common/package.json
  packages/metadata-common/style/index.css
  packages/metadata/package.json
  packages/metadata/style/index.css
  packages/pipeline-editor/package.json
  packages/python-editor/package.json
  packages/r-editor/package.json
  packages/script-editor/package.json
  packages/services/package.json
  packages/theme/package.json
  packages/ui-components/package.json
  setup.cfg
  setup.py
  tests/integration/codesnippet.ts
  tsconfig.base.json
  yarn.lock
Labels: component:build

#2505 Update custom component help link in VPE
  create-release.py
  packages/pipeline-editor/src/EmptyPipelineContent.tsx
Labels: component:pipeline-editor

#2503 Fix invalid KFP component URL references
  docs/source/user_guide/pipeline-components.md
Labels: kind:bug, area:documentation

#2495 Update to use Jupyterlab 3.3.0rc0
  .github/workflows/build.yml
  package.json
  packages/code-snippet/package.json
  packages/metadata-common/package.json
  packages/metadata/package.json
  packages/pipeline-editor/package.json
  packages/python-editor/package.json
  packages/r-editor/package.json
  packages/script-editor/package.json
  packages/services/package.json
  packages/theme/package.json
  packages/ui-components/package.json
  setup.py
  testutils/jest.config.js
  yarn.lock
Labels: external:Upstream

#2506 elyra-pipeline CLI: Pin doc link to the current release
  create-release.py
Labels: area:documentation, component:cli-tools
