Repository elyra-ai/elyra, pull requests merged in 2023-02, with the labels that each got.

#3097 Update function format to conform to black v23 linting
  elyra/airflow/operator.py
  elyra/elyra_app.py
  elyra/metadata/handlers.py
  elyra/metadata/schemasproviders.py
  elyra/pipeline/airflow/package_catalog_connector/airflow_package_catalog_connector.py
  elyra/pipeline/airflow/processor_airflow.py
  elyra/pipeline/airflow/provider_package_catalog_connector/airflow_provider_package_catalog_connector.py
  elyra/pipeline/component_catalog.py
  elyra/pipeline/handlers.py
  elyra/pipeline/kfp/kfp_authentication.py
  elyra/pipeline/local/processor_local.py
  elyra/pipeline/processor.py
  elyra/tests/metadata/test_handlers.py
  elyra/tests/metadata/test_metadata.py
  elyra/tests/metadata/test_metadata_app.py
  elyra/tests/metadata/test_utils.py
  elyra/tests/pipeline/airflow/test_processor_airflow.py
  elyra/tests/pipeline/local/test_pipeline_processor_local.py
  elyra/tests/pipeline/resources/components/airflow_test_operator_no_inputs.py
  elyra/tests/pipeline/resources/components/airflow_test_operator_type_hints.py
  elyra/tests/pipeline/test_pipeline_constructor.py
  elyra/tests/pipeline/test_validation.py
  elyra/tests/pipeline/util.py
Labels: component:build

#3098 Remove Python v3.7 from CI tests
  .github/workflows/build.yml
Labels: component:build

#3093 Fix KFP code generation issues for pipeline parameters
  elyra/pipeline/kfp/processor_kfp.py
  elyra/pipeline/properties.py
  elyra/templates/kubeflow/v1/generic_component_definition_template.jinja2
  elyra/templates/kubeflow/v1/python_dsl_template.jinja2
  elyra/tests/pipeline/test_properties.py
Labels: kind:bug, component:pipeline-editor, platform: pipeline-Kubeflow

#3101 Remove references to Python 3.7
  Makefile
  README.md
  create-release.py
  docs/source/getting_started/installation.md
  docs/source/recipes/running-elyra-in-air-gapped-environment.md
  elyra/airflow/bootstrapper.py
  elyra/airflow/operator.py
  elyra/kfp/bootstrapper.py
  elyra/pipeline/kfp/processor_kfp.py
  elyra/tests/pipeline/resources/validation_pipelines/kf_invalid_node_property_in_component.pipeline
  etc/generic/requirements-elyra-py37.txt
  etc/templates/setup.py
  pyproject.toml
  readthedocs.yml
Labels: component:build

#3106 Skip version check for incompatible version strings in `bootstrapper.py`
  elyra/airflow/bootstrapper.py
  elyra/kfp/bootstrapper.py
Labels: kind:bug, component:pipeline-runtime

#3112 Remove references to Jupyterlab 1.x and 2.x from documentation
  README.md
  SECURITY.md
  docs/source/developer_guide/development-workflow.md
  docs/source/getting_started/installation.md
Labels: area:documentation, status:Work in Progress

#3113 Bump kfp-tekton to 1.6.2 to pick up kfp 1.8.19
  pyproject.toml
Labels: component:build, external:Upstream, platform: pipeline-Kubeflow
