Repository elyra-ai/elyra, pull requests merged in 2023-03, with the labels that each got.

#3119 Hide binder links and references
  README.md
  create-release.py
  docs/source/getting_started/installation.md
  docs/source/getting_started/overview.md
Labels: kind:bug, area:documentation, component:build

#3118 Require Node.js version 18 (or later) in preparation for version 16 EOL
  README.md
  create-release.py
  docs/source/developer_guide/development-workflow.md
  docs/source/getting_started/installation.md
Labels: area:documentation, dependencies

#3114 Filter available runtimes based on configuration setting
  docs/source/images/user_guide/pipeline-editor-configuration/pipeline-editor-kfp-only-in-jupyterlab-launcher.png
  docs/source/images/user_guide/pipeline-editor-configuration/pipeline-editor-subset-in-jupyterlab-launcher.png
  docs/source/images/user_guide/pipeline-editor-configuration/pipeline-editor-tiles-in-jupyterlab-launcher.png
  docs/source/index.rst
  docs/source/user_guide/jupyterlab-interface.md
  docs/source/user_guide/pipeline-editor-configuration.md
  elyra/elyra_app.py
  elyra/pipeline/component_catalog.py
  elyra/pipeline/handlers.py
  elyra/pipeline/processor.py
  elyra/pipeline/registry.py
  elyra/pipeline/runtime_type.py
  elyra/templates/components/generic_properties_template.jinja2
  elyra/tests/pipeline/test_processor.py
  etc/docker/kubeflow/Dockerfile
  packages/metadata-common/src/MetadataWidget.tsx
  packages/pipeline-editor/src/ComponentCatalogsWidget.tsx
  packages/pipeline-editor/src/PipelineEditorWidget.tsx
  packages/pipeline-editor/src/PipelineService.tsx
  packages/pipeline-editor/src/RuntimesWidget.tsx
  packages/pipeline-editor/src/SubmitFileButtonExtension.tsx
  packages/pipeline-editor/src/index.ts
  tests/integration/pipeline.ts
  tests/support/commands.ts
Labels: kind:enhancement, component:pipeline-editor, component:pipeline-runtime

#3123 Update community resources
  docs/source/getting_started/getting-help.md
Labels: area:documentation

#3125 Lower floor for kfp-tekton dependency
  pyproject.toml
Labels: dependencies

#3135 Determine which kernel to use prior to notebook execution
  elyra/airflow/bootstrapper.py
  elyra/tests/airflow/resources/test-notebookA.ipynb
  elyra/tests/airflow/test_bootstrapper.py
Labels: kind:bug, platform: pipeline-Airflow

#3124 Add support for static bearer token authentication for KFP
  docs/source/user_guide/runtime-conf.md
  elyra/metadata/schemas/kfp.json
  elyra/pipeline/kfp/kfp_authentication.py
  elyra/tests/pipeline/kfp/test_kfp_authentication.py
Labels: kind:enhancement, platform: pipeline-Kubeflow

#3121 Add link to 3.15.0 new feature highlight blog post
  docs/source/getting_started/published-resources.md
Labels: area:documentation
