Repository elyra-ai/elyra, pull requests merged in 2024-08, with the labels that each got.

#3150 Allow users to include ssl_sa_certs via env vars for kfp_tekton client
  docs/source/user_guide/runtime-conf.md
  elyra/pipeline/kfp/kfp_authentication.py
  elyra/pipeline/kfp/processor_kfp.py
Labels: component:pipeline-runtime, status:Waiting for Author, platform: pipeline-Kubeflow

#3240 nbconvert version without lxml requirement and more
  etc/generic/requirements-elyra.txt
  pyproject.toml
Labels: dependencies, python

#3227 RFileOp PythonFileOp NotebookFileOp log stdout and stderr output to stdout always, S3 file put for run log output file made configurable
  elyra/airflow/bootstrapper.py
  elyra/kfp/bootstrapper.py
Labels: component:pipeline-editor, component:pipeline-runtime
